### ISSUE TITLE
[UX] SoarV2 - Display last run time & update time

### ISSUE THREAD

**Issue by fagat73** [soaringmeteo/soaringmeteo#121]
In SoarV2 it will be interesting to easily make availlable the model initialisation run time used (GFS or WRF)  and soaring meteo last update time.
Proposal :
->Display these 2 informations on the Sumary section
![image](https://github.com/soaringmeteo/soaringmeteo/assets/25865664/3483744f-04cc-4269-a3a5-41538f9ba2d0)

**Comment by julienrf** [comment]
Thank you for your suggestion. In general, we should be careful not to overload the user interface with too much information.

That being said, we could probably add this information to the first line:

![image](https://github.com/soaringmeteo/soaringmeteo/assets/332812/48981778-6c04-4ae5-a2f5-85c96ae1efc5)

I find it a bit too long but I am not sure how to shorten it without making it too cryptic.

Any suggestions?

**Comment by julienrf** [comment]
Here is another attempt:

![image](https://github.com/soaringmeteo/soaringmeteo/assets/332812/0876f9af-c842-44f6-8106-bd13d08edb32)

**Comment by fagat73** [comment]
Second attempt is indeed easier to read . Maybe just invert model name and coordinate (and altitude) as this information depend directly of the model grid. 
![image](https://github.com/soaringmeteo/soaringmeteo/assets/25865664/68763b16-0c5b-48bb-8572-4dae90691bd4)
