### ISSUE TITLE
Add support for language PL (polish)

### ISSUE THREAD

**Issue by ant2753** [soaringmeteo/soaringmeteo#138]
I am happy to provide translations into polish language.
Will you enable PL ?

**Comment by julienrf** [comment]
Hello @ant2753! Thank you for your interest. Yes, absolutely! I’ve just added it to the project configuration, you can follow the [translating](https://github.com/soaringmeteo/soaringmeteo/blob/main/TRANSLATING.md) guide to translate the messages in Polish.
