### ISSUE TITLE
Add support for language ES

### ISSUE THREAD

**Issue by Boran** [soaringmeteo/soaringmeteo#140]
Can we add the initial spanish? 
I'll will then do the machine translation and get it review by a native speaker at RVL

**Comment by julienrf** [comment]
I’ve just added Spanish to the configuration.

You can start adding translations here: https://fink.inlang.com/github.com/soaringmeteo/soaringmeteo?project=%2Ffrontend%2Fproject.inlang&lang=en&lang=es

**Comment by julienrf** [comment]
I close the issue since Spanish is now available.
