### ISSUE TITLE
Add support for language sk slovak

### ISSUE THREAD

**Issue by slapiar** [soaringmeteo/soaringmeteo#151]
Dears,
I will be happy to contribute by translating it into Slovak. I have been a hang glider pilot for 44 years. In Slovakia, there is a great lack of such tools for gliders and teaching aids for pupils. This condition reduces the safety and popularity of our beautiful sport.

Regards,

Slavomir Piar

**Comment by Boran** [comment]
Hi,

Great!

Question: are you a software developer,  i.e. have you used github before?

Regards,

Sean

**Comment by slapiar** [comment]
Hi,

my answer is Yes, I have used github before.
Regards,

Slavo

št 4. 7. 2024 o 12:43 Sean Boran ***@***.***> napísal(a):

> Hi,
>
> Great!
>
> Question: are you a software developer, i.e. have you used github before?
>
> Regards,
>
> Sean
>

**Comment by Boran** [comment]
First step is to add the language, PR created https://github.com/soaringmeteo/soaringmeteo/pull/152, 

Slavo, then, the process is described here https://github.com/Boran/soaringmeteo_transDE/blob/main/TRANSLATING.md

**Comment by slapiar** [comment]
O.K. forked

so 6. 7. 2024 o 13:26 Sean Boran ***@***.***> napísal(a):

**Comment by julienrf** [comment]
Thank you @slapiar for your help! We just enabled Slovak in the project configuration. You should now be able to translate the messages by following the guide here: https://github.com/soaringmeteo/soaringmeteo/blob/main/TRANSLATING.md#fix-or-complete-an-existing-translation

**Comment by Boran** [comment]
Was there a problems with https://github.com/soaringmeteo/soaringmeteo/pull/154 ?

**Comment by Boran** [comment]
See https://github.com/soaringmeteo/soaringmeteo/issues/152

**Comment by slapiar** [comment]
Hi,
Sorry, I didn't understand. In the previous comment, you wrote that you enabled Slovak, but I don't see the change on the frontend. I'll be happy to do whatever else is needed. Please let me know. Have a good flight!

**Comment by julienrf** [comment]
Hi @slapiar, the Slovak language is available in the [translation tool](https://fink.inlang.com/github.com/soaringmeteo/soaringmeteo?project=%2Ffrontend%2Fproject.inlang&lang=en&lang=sk) but the translation you contributed in #155 has not been deployed yet.

Could you please have look at https://github.com/soaringmeteo/soaringmeteo/pull/155#discussion_r1673809650?

**Comment by julienrf** [comment]
Thank you for your help @slapiar, I just enabled your translation in ef5300a and re-deployed the application. It should be updated soon by your browser.

**Comment by slapiar** [comment]
Waw, great. Thanks for your patience.

Best regards,

Slavo Piar

pi 12. 7. 2024 o 10:10 Julien Richard-Foy ***@***.***>
napísal(a):

**Comment by slapiar** [comment]
Hi, well it function on my browsers.
I offer to do a translation of documentation, or contributions from Jean
Oberson, including those in .pdf format. If those texts were available in
English or French, I would like to make them available in Slovak to my
colleagues and especially to novice pilots.
Personally, I consider gliding meteorology and the experience of top pilots
to be the most important "rescue parachute" for every glider pilot.
Regards,

Slavo

pi 12. 7. 2024 o 10:09 Julien Richard-Foy ***@***.***>
napísal(a):

**Comment by julienrf** [comment]
Unfortunately, we don’t have the source files for those PDF documents.

**Comment by slapiar** [comment]
Hi, I don't understand, Please specify exactly.

pi 12. 7. 2024 o 10:01 Julien Richard-Foy ***@***.***>
napísal(a):

**Comment by slapiar** [comment]
No problem.
If I get permission to do the translations, I can choose the texts from the
.pdf. I would like to post them on my site that I am about to make.

pi 12. 7. 2024 o 11:17 Julien Richard-Foy ***@***.***>
napísal(a):

**Comment by julienrf** [comment]
Sure, please just credit the source :)

**Comment by slapiar** [comment]
Samozrejme, hrdo. Thanks.
But, I have one problem. Now, reading my translation I find minor flaws in
the translation of the messages. I'll fix it again, okay?

Slavo

pi 12. 7. 2024 o 12:37 Julien Richard-Foy ***@***.***>
napísal(a):

**Comment by julienrf** [comment]
> reading my translation I find minor flaws in the translation of the messages. I'll fix it again, okay?

Sure, feel free to improve the translation. You can use this link to edit your messages: https://fink.inlang.com/github.com/soaringmeteo/soaringmeteo?project=%2Ffrontend%2Fproject.inlang&lang=en&lang=sk

**Comment by slapiar** [comment]
Better for me is upload sk.json. I was sent.

pi 12. 7. 2024 o 15:20 Julien Richard-Foy ***@***.***>
napísal(a):
