### ISSUE TITLE
Consider using OpenLayers instead of Leaflet

### ISSUE THREAD

**Issue by julienrf** [soaringmeteo/soaringmeteo#20]
[OpenLayers](https://openlayers.org/) supports [raster reprojection](https://openlayers.org/en/latest/doc/tutorials/raster-reprojection.html) out of the box, which would be useful to display the forecast data as an overlay on the map. We currently use Leaflet, where we have an _ad hoc_ implementation of the [projection of the GFS grid on the map](https://github.com/soaringmeteo/soaringmeteo/blob/aa2ebe873cd82346e4490e80fca8310995ce95f8/frontend/src/CanvasLayer.ts).

Also, OpenLayers seems to support the [WMS provided by Météo France](https://donneespubliques.meteofrance.fr/?fond=produit&id_produit=131&id_rubrique=51).

OpenLayers seems powerful, however, the following points need to be investigated:

- would this increase the size of the application bundle?
- OpenLayers can easily project pixels in the map, but what about some more advanced shape, like a wind barbell?

**Comment by julienrf** [comment]
> * OpenLayers can easily project pixels in the map, but what about some more advanced shape, like a wind barbell?

There seems to be a way to project more complex shapes, given what we can play with [here](https://donneespubliques.meteofrance.fr/?fond=produit&id_produit=130&id_rubrique=51):

![Screenshot from 2021-07-08 10-31-54](https://user-images.githubusercontent.com/332812/124889831-c0c48780-dfd7-11eb-9d08-293f7542fbe1.png)

**Comment by Boran** [comment]
That would be good, perhaps also allowing a nicer way to show cloud density than the current circles?
