### ISSUE TITLE
Meteogram navigation

### ISSUE THREAD

**Issue by Boran** [soaringmeteo/soaringmeteo#75]
I open a meteogram, and navigate using the dates in the red part.
The data in the green part does not update
The dates at the bottom (ping), do, also change correctly
![image](https://user-images.githubusercontent.com/405059/234476475-f72a5a49-b779-4385-8f25-64e43f911055.png)

Tested on windows: Chrome and Edge. Androis.

**Comment by julienrf** [comment]
I don’t understand what you would expect. The meteogram shows the forecast for a location over time. Below the date “Wed, Apr 26” you see the forecast for the 26th of April, below the date “Thu, Apr 27” you see the forecast for the 27th of April, and so on. So, the meteogram shows a forecast regardless of the selected time.

The selected time impacts what you see on the map, and sounding diagrams.

**Comment by Boran** [comment]
Yes you are right closing.
It updates the map in the background. Not sure what I was expected when I wrote this :-).
