### ISSUE TITLE
Enhancing computing speed

### ISSUE THREAD

**Issue by tcibils** [soaringmeteo/soaringmeteo#83]
On 24.03.2021, there has been a change in the distribution format of weather data used for the computation, which interrupted the service at the time.

- Previously, the first forecasting soarWRF results for the day after tomorrow were available around ~8:30 or 9:00am.
- From then on, forecasting results for the day after tomorrow became available around 11:30am.

Having these forecasts earlier was very handy, especially for week days, as it allowed for easier day-off planning and eased relations with management. Would there be a way to gain a bit a computing speed, to have the results earlier again?

SoarV2, XCTherm and others are good backup solution for such purpose, but I thought I'd still open a ticket here 😃 Have a good day!

**Comment by julienrf** [comment]
Hello,
I don't think that event had such an impact on the time we produce WRF forecasts. The forecast in two days has always been available around 9:30Z, which means 10:30 in winter and 11:30 in summer.
That being said, the NOAA recently upgraded their infrastructure, so it is possible that the data we need to run the model is now available about 30 min earlier. I will have a look.

**Comment by julienrf** [comment]
I am happy to report that we renewed our servers and the new machines are more powerful than before. As a consequence, the forecast results are now available a bit earlier than before (e.g., at 08:30Z for d+2).

I am marking this issue as resolved.
