### ISSUE TITLE
Expose Soaringmeteo API

### ISSUE THREAD

**Issue by tcibils** [soaringmeteo/soaringmeteo#84]
A potentially interesting feature could be to expose an backend API with documentation to the outside world. This could allow other developers to build a separated, more intuitive front-end, based on the existing computation, and let the team focus on the data gathering and model building side. This would nevertheless come at the cost of an API management topic, potentially with versioning etc.

**Comment by Boran** [comment]
Soar V2 is open source, you could analyse and contribue code. 
Are you capable of creating such front ends?

**Comment by tcibils** [comment]
I am trying to go through the code indeed, but as I am not familiar with its architecture, and neither with Scala, it's not that easy for me. That being said, I am not a front-end developer myself, so I was rather thinking that the encapsulation an API would provide could make it easier for a passing-by front-end dev to help 😄

**Comment by julienrf** [comment]
I propose we close this issue since we currently have no real demand for such an API. This could be revisited anytime in the future.
